# Generated by Django 4.0.6 on 2022-07-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
